server:
  port: 8002
spring:
  application:
    name: blogmx-upload
  servlet:
    multipart:
      max-file-size: 5MB # 限制文件上传的大小
  datasource: # 配置数据源
    url: jdbc:mysql://47.99.81.136:3306/blogmx?characterEncoding=utf-8
    username: root
    password: sjg2607794330
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10001/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

fdfs:
  so-timeout: 1501 # 超时时间
  connect-timeout: 601 # 连接超时时间
  thumb-image: # 缩略图
    width: 60
    height: 60
  tracker-list: 47.99.81.136:22122 # tracker地址：你的服务器地址+端口（默认是22122）

mybatis:
  type-aliases-package: com.blogmx.pojo # 配置实体类
  configuration:
    default-statement-timeout: 30000

