server:
  port: 8001
spring:
  application:
    name: blogmx-blog
  servlet:
    multipart:
      max-file-size: 5MB # 限制文件上传的大小
  thymeleaf:
    cache: false
  datasource: # 配置数据源
    url: jdbc:mysql://47.99.81.136:3306/blogmx?characterEncoding=utf-8&autoReconnect=true
    username: root
    password: sjg2607794330
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      max-lifetime: 30000
      connection-test-query: SELECT 1
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 47.99.81.136:9300
  redis:
    host: 47.99.81.136
      # Redis服务器连接端口
    port: 6379
    jedis:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        # 连接池中的最小空闲连接
        max-idle: 10
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 100000
    # 连接超时时间（毫秒）
    timeout: 5000
    #默认是索引为0的数据库
    database: 0
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10001/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 5秒钟发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
mybatis:
  type-aliases-package: com.blogmx.pojo # 配置实体类
  configuration:
    default-statement-timeout: 30000

fdfs:
  so-timeout: 1501 # 超时时间
  connect-timeout: 601 # 连接超时时间
  thumb-image: # 缩略图
    width: 60
    height: 60
  tracker-list: 47.99.81.136:22122 # tracker地址：你的服务器地址+端口（默认是22122）


